// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserDevice is the predicate function for userdevice builders.
type UserDevice func(*sql.Selector)

// UserMeta is the predicate function for usermeta builders.
type UserMeta func(*sql.Selector)

// UserOAuthProvider is the predicate function for useroauthprovider builders.
type UserOAuthProvider func(*sql.Selector)
