// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sundaytycoon/buttons-api/internal/storage/servicedb/ent/predicate"
	"github.com/sundaytycoon/buttons-api/internal/storage/servicedb/ent/user"
	"github.com/sundaytycoon/buttons-api/internal/storage/servicedb/ent/userdevice"
)

// UserDeviceUpdate is the builder for updating UserDevice entities.
type UserDeviceUpdate struct {
	config
	hooks    []Hook
	mutation *UserDeviceMutation
}

// Where appends a list predicates to the UserDeviceUpdate builder.
func (udu *UserDeviceUpdate) Where(ps ...predicate.UserDevice) *UserDeviceUpdate {
	udu.mutation.Where(ps...)
	return udu
}

// SetUserID sets the "user_id" field.
func (udu *UserDeviceUpdate) SetUserID(s string) *UserDeviceUpdate {
	udu.mutation.SetUserID(s)
	return udu
}

// SetCreatedAt sets the "created_at" field.
func (udu *UserDeviceUpdate) SetCreatedAt(t time.Time) *UserDeviceUpdate {
	udu.mutation.SetCreatedAt(t)
	return udu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (udu *UserDeviceUpdate) SetNillableCreatedAt(t *time.Time) *UserDeviceUpdate {
	if t != nil {
		udu.SetCreatedAt(*t)
	}
	return udu
}

// SetCreatedBy sets the "created_by" field.
func (udu *UserDeviceUpdate) SetCreatedBy(s string) *UserDeviceUpdate {
	udu.mutation.SetCreatedBy(s)
	return udu
}

// SetUpdatedAt sets the "updated_at" field.
func (udu *UserDeviceUpdate) SetUpdatedAt(t time.Time) *UserDeviceUpdate {
	udu.mutation.SetUpdatedAt(t)
	return udu
}

// SetUpdatedBy sets the "updated_by" field.
func (udu *UserDeviceUpdate) SetUpdatedBy(s string) *UserDeviceUpdate {
	udu.mutation.SetUpdatedBy(s)
	return udu
}

// SetStatus sets the "status" field.
func (udu *UserDeviceUpdate) SetStatus(u userdevice.Status) *UserDeviceUpdate {
	udu.mutation.SetStatus(u)
	return udu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (udu *UserDeviceUpdate) SetNillableStatus(u *userdevice.Status) *UserDeviceUpdate {
	if u != nil {
		udu.SetStatus(*u)
	}
	return udu
}

// SetType sets the "type" field.
func (udu *UserDeviceUpdate) SetType(u userdevice.Type) *UserDeviceUpdate {
	udu.mutation.SetType(u)
	return udu
}

// SetOs sets the "os" field.
func (udu *UserDeviceUpdate) SetOs(u userdevice.Os) *UserDeviceUpdate {
	udu.mutation.SetOs(u)
	return udu
}

// SetPlatform sets the "platform" field.
func (udu *UserDeviceUpdate) SetPlatform(u userdevice.Platform) *UserDeviceUpdate {
	udu.mutation.SetPlatform(u)
	return udu
}

// SetUser sets the "user" edge to the User entity.
func (udu *UserDeviceUpdate) SetUser(u *User) *UserDeviceUpdate {
	return udu.SetUserID(u.ID)
}

// Mutation returns the UserDeviceMutation object of the builder.
func (udu *UserDeviceUpdate) Mutation() *UserDeviceMutation {
	return udu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (udu *UserDeviceUpdate) ClearUser() *UserDeviceUpdate {
	udu.mutation.ClearUser()
	return udu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (udu *UserDeviceUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	udu.defaults()
	if len(udu.hooks) == 0 {
		if err = udu.check(); err != nil {
			return 0, err
		}
		affected, err = udu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserDeviceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = udu.check(); err != nil {
				return 0, err
			}
			udu.mutation = mutation
			affected, err = udu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(udu.hooks) - 1; i >= 0; i-- {
			if udu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = udu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, udu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (udu *UserDeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := udu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (udu *UserDeviceUpdate) Exec(ctx context.Context) error {
	_, err := udu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (udu *UserDeviceUpdate) ExecX(ctx context.Context) {
	if err := udu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (udu *UserDeviceUpdate) defaults() {
	if _, ok := udu.mutation.UpdatedAt(); !ok {
		v := userdevice.UpdateDefaultUpdatedAt()
		udu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (udu *UserDeviceUpdate) check() error {
	if v, ok := udu.mutation.Status(); ok {
		if err := userdevice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserDevice.status": %w`, err)}
		}
	}
	if v, ok := udu.mutation.GetType(); ok {
		if err := userdevice.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "UserDevice.type": %w`, err)}
		}
	}
	if v, ok := udu.mutation.Os(); ok {
		if err := userdevice.OsValidator(v); err != nil {
			return &ValidationError{Name: "os", err: fmt.Errorf(`ent: validator failed for field "UserDevice.os": %w`, err)}
		}
	}
	if v, ok := udu.mutation.Platform(); ok {
		if err := userdevice.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UserDevice.platform": %w`, err)}
		}
	}
	if _, ok := udu.mutation.UserID(); udu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UserDevice.user"`)
	}
	return nil
}

func (udu *UserDeviceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userdevice.Table,
			Columns: userdevice.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: userdevice.FieldID,
			},
		},
	}
	if ps := udu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := udu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userdevice.FieldCreatedAt,
		})
	}
	if value, ok := udu.mutation.CreatedBy(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userdevice.FieldCreatedBy,
		})
	}
	if value, ok := udu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userdevice.FieldUpdatedAt,
		})
	}
	if value, ok := udu.mutation.UpdatedBy(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userdevice.FieldUpdatedBy,
		})
	}
	if value, ok := udu.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: userdevice.FieldStatus,
		})
	}
	if value, ok := udu.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: userdevice.FieldType,
		})
	}
	if value, ok := udu.mutation.Os(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: userdevice.FieldOs,
		})
	}
	if value, ok := udu.mutation.Platform(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: userdevice.FieldPlatform,
		})
	}
	if udu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userdevice.UserTable,
			Columns: []string{userdevice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := udu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userdevice.UserTable,
			Columns: []string{userdevice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, udu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userdevice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// UserDeviceUpdateOne is the builder for updating a single UserDevice entity.
type UserDeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserDeviceMutation
}

// SetUserID sets the "user_id" field.
func (uduo *UserDeviceUpdateOne) SetUserID(s string) *UserDeviceUpdateOne {
	uduo.mutation.SetUserID(s)
	return uduo
}

// SetCreatedAt sets the "created_at" field.
func (uduo *UserDeviceUpdateOne) SetCreatedAt(t time.Time) *UserDeviceUpdateOne {
	uduo.mutation.SetCreatedAt(t)
	return uduo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uduo *UserDeviceUpdateOne) SetNillableCreatedAt(t *time.Time) *UserDeviceUpdateOne {
	if t != nil {
		uduo.SetCreatedAt(*t)
	}
	return uduo
}

// SetCreatedBy sets the "created_by" field.
func (uduo *UserDeviceUpdateOne) SetCreatedBy(s string) *UserDeviceUpdateOne {
	uduo.mutation.SetCreatedBy(s)
	return uduo
}

// SetUpdatedAt sets the "updated_at" field.
func (uduo *UserDeviceUpdateOne) SetUpdatedAt(t time.Time) *UserDeviceUpdateOne {
	uduo.mutation.SetUpdatedAt(t)
	return uduo
}

// SetUpdatedBy sets the "updated_by" field.
func (uduo *UserDeviceUpdateOne) SetUpdatedBy(s string) *UserDeviceUpdateOne {
	uduo.mutation.SetUpdatedBy(s)
	return uduo
}

// SetStatus sets the "status" field.
func (uduo *UserDeviceUpdateOne) SetStatus(u userdevice.Status) *UserDeviceUpdateOne {
	uduo.mutation.SetStatus(u)
	return uduo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (uduo *UserDeviceUpdateOne) SetNillableStatus(u *userdevice.Status) *UserDeviceUpdateOne {
	if u != nil {
		uduo.SetStatus(*u)
	}
	return uduo
}

// SetType sets the "type" field.
func (uduo *UserDeviceUpdateOne) SetType(u userdevice.Type) *UserDeviceUpdateOne {
	uduo.mutation.SetType(u)
	return uduo
}

// SetOs sets the "os" field.
func (uduo *UserDeviceUpdateOne) SetOs(u userdevice.Os) *UserDeviceUpdateOne {
	uduo.mutation.SetOs(u)
	return uduo
}

// SetPlatform sets the "platform" field.
func (uduo *UserDeviceUpdateOne) SetPlatform(u userdevice.Platform) *UserDeviceUpdateOne {
	uduo.mutation.SetPlatform(u)
	return uduo
}

// SetUser sets the "user" edge to the User entity.
func (uduo *UserDeviceUpdateOne) SetUser(u *User) *UserDeviceUpdateOne {
	return uduo.SetUserID(u.ID)
}

// Mutation returns the UserDeviceMutation object of the builder.
func (uduo *UserDeviceUpdateOne) Mutation() *UserDeviceMutation {
	return uduo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (uduo *UserDeviceUpdateOne) ClearUser() *UserDeviceUpdateOne {
	uduo.mutation.ClearUser()
	return uduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uduo *UserDeviceUpdateOne) Select(field string, fields ...string) *UserDeviceUpdateOne {
	uduo.fields = append([]string{field}, fields...)
	return uduo
}

// Save executes the query and returns the updated UserDevice entity.
func (uduo *UserDeviceUpdateOne) Save(ctx context.Context) (*UserDevice, error) {
	var (
		err  error
		node *UserDevice
	)
	uduo.defaults()
	if len(uduo.hooks) == 0 {
		if err = uduo.check(); err != nil {
			return nil, err
		}
		node, err = uduo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserDeviceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uduo.check(); err != nil {
				return nil, err
			}
			uduo.mutation = mutation
			node, err = uduo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uduo.hooks) - 1; i >= 0; i-- {
			if uduo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uduo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uduo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (uduo *UserDeviceUpdateOne) SaveX(ctx context.Context) *UserDevice {
	node, err := uduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uduo *UserDeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := uduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uduo *UserDeviceUpdateOne) ExecX(ctx context.Context) {
	if err := uduo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uduo *UserDeviceUpdateOne) defaults() {
	if _, ok := uduo.mutation.UpdatedAt(); !ok {
		v := userdevice.UpdateDefaultUpdatedAt()
		uduo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uduo *UserDeviceUpdateOne) check() error {
	if v, ok := uduo.mutation.Status(); ok {
		if err := userdevice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserDevice.status": %w`, err)}
		}
	}
	if v, ok := uduo.mutation.GetType(); ok {
		if err := userdevice.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "UserDevice.type": %w`, err)}
		}
	}
	if v, ok := uduo.mutation.Os(); ok {
		if err := userdevice.OsValidator(v); err != nil {
			return &ValidationError{Name: "os", err: fmt.Errorf(`ent: validator failed for field "UserDevice.os": %w`, err)}
		}
	}
	if v, ok := uduo.mutation.Platform(); ok {
		if err := userdevice.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UserDevice.platform": %w`, err)}
		}
	}
	if _, ok := uduo.mutation.UserID(); uduo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UserDevice.user"`)
	}
	return nil
}

func (uduo *UserDeviceUpdateOne) sqlSave(ctx context.Context) (_node *UserDevice, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userdevice.Table,
			Columns: userdevice.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: userdevice.FieldID,
			},
		},
	}
	id, ok := uduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserDevice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userdevice.FieldID)
		for _, f := range fields {
			if !userdevice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userdevice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uduo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userdevice.FieldCreatedAt,
		})
	}
	if value, ok := uduo.mutation.CreatedBy(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userdevice.FieldCreatedBy,
		})
	}
	if value, ok := uduo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userdevice.FieldUpdatedAt,
		})
	}
	if value, ok := uduo.mutation.UpdatedBy(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userdevice.FieldUpdatedBy,
		})
	}
	if value, ok := uduo.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: userdevice.FieldStatus,
		})
	}
	if value, ok := uduo.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: userdevice.FieldType,
		})
	}
	if value, ok := uduo.mutation.Os(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: userdevice.FieldOs,
		})
	}
	if value, ok := uduo.mutation.Platform(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: userdevice.FieldPlatform,
		})
	}
	if uduo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userdevice.UserTable,
			Columns: []string{userdevice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uduo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userdevice.UserTable,
			Columns: []string{userdevice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserDevice{config: uduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userdevice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
