// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/sundaytycoon/buttons-api/ent/schema"
	"github.com/sundaytycoon/buttons-api/ent/user"
	"github.com/sundaytycoon/buttons-api/ent/userdevice"
	"github.com/sundaytycoon/buttons-api/ent/usermeta"
	"github.com/sundaytycoon/buttons-api/ent/useroauthprovider"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[3].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescSignup is the schema descriptor for signup field.
	userDescSignup := userFields[7].Descriptor()
	// user.DefaultSignup holds the default value on creation for the signup field.
	user.DefaultSignup = userDescSignup.Default.(bool)
	userdeviceFields := schema.UserDevice{}.Fields()
	_ = userdeviceFields
	// userdeviceDescCreatedAt is the schema descriptor for created_at field.
	userdeviceDescCreatedAt := userdeviceFields[2].Descriptor()
	// userdevice.DefaultCreatedAt holds the default value on creation for the created_at field.
	userdevice.DefaultCreatedAt = userdeviceDescCreatedAt.Default.(func() time.Time)
	// userdeviceDescUpdatedAt is the schema descriptor for updated_at field.
	userdeviceDescUpdatedAt := userdeviceFields[4].Descriptor()
	// userdevice.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userdevice.DefaultUpdatedAt = userdeviceDescUpdatedAt.Default.(func() time.Time)
	// userdevice.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userdevice.UpdateDefaultUpdatedAt = userdeviceDescUpdatedAt.UpdateDefault.(func() time.Time)
	usermetaFields := schema.UserMeta{}.Fields()
	_ = usermetaFields
	// usermetaDescCreatedAt is the schema descriptor for created_at field.
	usermetaDescCreatedAt := usermetaFields[2].Descriptor()
	// usermeta.DefaultCreatedAt holds the default value on creation for the created_at field.
	usermeta.DefaultCreatedAt = usermetaDescCreatedAt.Default.(func() time.Time)
	// usermetaDescUpdatedAt is the schema descriptor for updated_at field.
	usermetaDescUpdatedAt := usermetaFields[4].Descriptor()
	// usermeta.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	usermeta.DefaultUpdatedAt = usermetaDescUpdatedAt.Default.(func() time.Time)
	// usermeta.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	usermeta.UpdateDefaultUpdatedAt = usermetaDescUpdatedAt.UpdateDefault.(func() time.Time)
	useroauthproviderFields := schema.UserOAuthProvider{}.Fields()
	_ = useroauthproviderFields
	// useroauthproviderDescCreatedAt is the schema descriptor for created_at field.
	useroauthproviderDescCreatedAt := useroauthproviderFields[2].Descriptor()
	// useroauthprovider.DefaultCreatedAt holds the default value on creation for the created_at field.
	useroauthprovider.DefaultCreatedAt = useroauthproviderDescCreatedAt.Default.(func() time.Time)
	// useroauthproviderDescUpdatedAt is the schema descriptor for updated_at field.
	useroauthproviderDescUpdatedAt := useroauthproviderFields[4].Descriptor()
	// useroauthprovider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	useroauthprovider.DefaultUpdatedAt = useroauthproviderDescUpdatedAt.Default.(func() time.Time)
	// useroauthprovider.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	useroauthprovider.UpdateDefaultUpdatedAt = useroauthproviderDescUpdatedAt.UpdateDefault.(func() time.Time)
}
