// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/sundaytycoon/buttons-api/ent/user"
	"github.com/sundaytycoon/buttons-api/ent/usermeta"
)

// UserMeta is the model entity for the UserMeta schema.
type UserMeta struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	// 해당 row를 최초로 만든 시간은 언제인지?
	CreatedAt time.Time `json:"created_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	// 해당 row를 최초로 만든 주체는 누구인지?
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	// 해당 row를 수정한 마지막 시간은 언제인지
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	// 해당 row를 수정한 마지막 주체 누구인지
	UpdatedBy string `json:"updated_by,omitempty"`
	// Profile holds the value of the "profile" field.
	// 어떤 Oauth provider를 이용하였는지?
	Profile string `json:"profile,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserMetaQuery when eager-loading is set.
	Edges     UserMetaEdges `json:"edges"`
	user_meta *string
}

// UserMetaEdges holds the relations/edges for other nodes in the graph.
type UserMetaEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserMetaEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// The edge user was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserMeta) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case usermeta.FieldID, usermeta.FieldUserID, usermeta.FieldCreatedBy, usermeta.FieldUpdatedBy, usermeta.FieldProfile:
			values[i] = new(sql.NullString)
		case usermeta.FieldCreatedAt, usermeta.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case usermeta.ForeignKeys[0]: // user_meta
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type UserMeta", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserMeta fields.
func (um *UserMeta) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usermeta.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				um.ID = value.String
			}
		case usermeta.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				um.UserID = value.String
			}
		case usermeta.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				um.CreatedAt = value.Time
			}
		case usermeta.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				um.CreatedBy = value.String
			}
		case usermeta.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				um.UpdatedAt = value.Time
			}
		case usermeta.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				um.UpdatedBy = value.String
			}
		case usermeta.FieldProfile:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile", values[i])
			} else if value.Valid {
				um.Profile = value.String
			}
		case usermeta.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_meta", values[i])
			} else if value.Valid {
				um.user_meta = new(string)
				*um.user_meta = value.String
			}
		}
	}
	return nil
}

// QueryUser queries the "user" edge of the UserMeta entity.
func (um *UserMeta) QueryUser() *UserQuery {
	return (&UserMetaClient{config: um.config}).QueryUser(um)
}

// Update returns a builder for updating this UserMeta.
// Note that you need to call UserMeta.Unwrap() before calling this method if this UserMeta
// was returned from a transaction, and the transaction was committed or rolled back.
func (um *UserMeta) Update() *UserMetaUpdateOne {
	return (&UserMetaClient{config: um.config}).UpdateOne(um)
}

// Unwrap unwraps the UserMeta entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (um *UserMeta) Unwrap() *UserMeta {
	tx, ok := um.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserMeta is not a transactional entity")
	}
	um.config.driver = tx.drv
	return um
}

// String implements the fmt.Stringer.
func (um *UserMeta) String() string {
	var builder strings.Builder
	builder.WriteString("UserMeta(")
	builder.WriteString(fmt.Sprintf("id=%v", um.ID))
	builder.WriteString(", user_id=")
	builder.WriteString(um.UserID)
	builder.WriteString(", created_at=")
	builder.WriteString(um.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", created_by=")
	builder.WriteString(um.CreatedBy)
	builder.WriteString(", updated_at=")
	builder.WriteString(um.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_by=")
	builder.WriteString(um.UpdatedBy)
	builder.WriteString(", profile=")
	builder.WriteString(um.Profile)
	builder.WriteByte(')')
	return builder.String()
}

// UserMetaSlice is a parsable slice of UserMeta.
type UserMetaSlice []*UserMeta

func (um UserMetaSlice) config(cfg config) {
	for _i := range um {
		um[_i].config = cfg
	}
}
