// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sundaytycoon/buttons-api/ent/predicate"
	"github.com/sundaytycoon/buttons-api/ent/user"
	"github.com/sundaytycoon/buttons-api/ent/useroauthprovider"
)

// UserOAuthProviderQuery is the builder for querying UserOAuthProvider entities.
type UserOAuthProviderQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserOAuthProvider
	// eager-loading edges.
	withUser *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserOAuthProviderQuery builder.
func (uopq *UserOAuthProviderQuery) Where(ps ...predicate.UserOAuthProvider) *UserOAuthProviderQuery {
	uopq.predicates = append(uopq.predicates, ps...)
	return uopq
}

// Limit adds a limit step to the query.
func (uopq *UserOAuthProviderQuery) Limit(limit int) *UserOAuthProviderQuery {
	uopq.limit = &limit
	return uopq
}

// Offset adds an offset step to the query.
func (uopq *UserOAuthProviderQuery) Offset(offset int) *UserOAuthProviderQuery {
	uopq.offset = &offset
	return uopq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uopq *UserOAuthProviderQuery) Unique(unique bool) *UserOAuthProviderQuery {
	uopq.unique = &unique
	return uopq
}

// Order adds an order step to the query.
func (uopq *UserOAuthProviderQuery) Order(o ...OrderFunc) *UserOAuthProviderQuery {
	uopq.order = append(uopq.order, o...)
	return uopq
}

// QueryUser chains the current query on the "user" edge.
func (uopq *UserOAuthProviderQuery) QueryUser() *UserQuery {
	query := &UserQuery{config: uopq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uopq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uopq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(useroauthprovider.Table, useroauthprovider.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, useroauthprovider.UserTable, useroauthprovider.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(uopq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserOAuthProvider entity from the query.
// Returns a *NotFoundError when no UserOAuthProvider was found.
func (uopq *UserOAuthProviderQuery) First(ctx context.Context) (*UserOAuthProvider, error) {
	nodes, err := uopq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{useroauthprovider.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uopq *UserOAuthProviderQuery) FirstX(ctx context.Context) *UserOAuthProvider {
	node, err := uopq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserOAuthProvider ID from the query.
// Returns a *NotFoundError when no UserOAuthProvider ID was found.
func (uopq *UserOAuthProviderQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = uopq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{useroauthprovider.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uopq *UserOAuthProviderQuery) FirstIDX(ctx context.Context) string {
	id, err := uopq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserOAuthProvider entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one UserOAuthProvider entity is not found.
// Returns a *NotFoundError when no UserOAuthProvider entities are found.
func (uopq *UserOAuthProviderQuery) Only(ctx context.Context) (*UserOAuthProvider, error) {
	nodes, err := uopq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{useroauthprovider.Label}
	default:
		return nil, &NotSingularError{useroauthprovider.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uopq *UserOAuthProviderQuery) OnlyX(ctx context.Context) *UserOAuthProvider {
	node, err := uopq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserOAuthProvider ID in the query.
// Returns a *NotSingularError when exactly one UserOAuthProvider ID is not found.
// Returns a *NotFoundError when no entities are found.
func (uopq *UserOAuthProviderQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = uopq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{useroauthprovider.Label}
	default:
		err = &NotSingularError{useroauthprovider.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uopq *UserOAuthProviderQuery) OnlyIDX(ctx context.Context) string {
	id, err := uopq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserOAuthProviders.
func (uopq *UserOAuthProviderQuery) All(ctx context.Context) ([]*UserOAuthProvider, error) {
	if err := uopq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return uopq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (uopq *UserOAuthProviderQuery) AllX(ctx context.Context) []*UserOAuthProvider {
	nodes, err := uopq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserOAuthProvider IDs.
func (uopq *UserOAuthProviderQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := uopq.Select(useroauthprovider.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uopq *UserOAuthProviderQuery) IDsX(ctx context.Context) []string {
	ids, err := uopq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uopq *UserOAuthProviderQuery) Count(ctx context.Context) (int, error) {
	if err := uopq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return uopq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (uopq *UserOAuthProviderQuery) CountX(ctx context.Context) int {
	count, err := uopq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uopq *UserOAuthProviderQuery) Exist(ctx context.Context) (bool, error) {
	if err := uopq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return uopq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (uopq *UserOAuthProviderQuery) ExistX(ctx context.Context) bool {
	exist, err := uopq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserOAuthProviderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uopq *UserOAuthProviderQuery) Clone() *UserOAuthProviderQuery {
	if uopq == nil {
		return nil
	}
	return &UserOAuthProviderQuery{
		config:     uopq.config,
		limit:      uopq.limit,
		offset:     uopq.offset,
		order:      append([]OrderFunc{}, uopq.order...),
		predicates: append([]predicate.UserOAuthProvider{}, uopq.predicates...),
		withUser:   uopq.withUser.Clone(),
		// clone intermediate query.
		sql:  uopq.sql.Clone(),
		path: uopq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (uopq *UserOAuthProviderQuery) WithUser(opts ...func(*UserQuery)) *UserOAuthProviderQuery {
	query := &UserQuery{config: uopq.config}
	for _, opt := range opts {
		opt(query)
	}
	uopq.withUser = query
	return uopq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserOAuthProvider.Query().
//		GroupBy(useroauthprovider.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (uopq *UserOAuthProviderQuery) GroupBy(field string, fields ...string) *UserOAuthProviderGroupBy {
	group := &UserOAuthProviderGroupBy{config: uopq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := uopq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return uopq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//	}
//
//	client.UserOAuthProvider.Query().
//		Select(useroauthprovider.FieldUserID).
//		Scan(ctx, &v)
//
func (uopq *UserOAuthProviderQuery) Select(fields ...string) *UserOAuthProviderSelect {
	uopq.fields = append(uopq.fields, fields...)
	return &UserOAuthProviderSelect{UserOAuthProviderQuery: uopq}
}

func (uopq *UserOAuthProviderQuery) prepareQuery(ctx context.Context) error {
	for _, f := range uopq.fields {
		if !useroauthprovider.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uopq.path != nil {
		prev, err := uopq.path(ctx)
		if err != nil {
			return err
		}
		uopq.sql = prev
	}
	return nil
}

func (uopq *UserOAuthProviderQuery) sqlAll(ctx context.Context) ([]*UserOAuthProvider, error) {
	var (
		nodes       = []*UserOAuthProvider{}
		_spec       = uopq.querySpec()
		loadedTypes = [1]bool{
			uopq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &UserOAuthProvider{config: uopq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, uopq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := uopq.withUser; query != nil {
		ids := make([]string, 0, len(nodes))
		nodeids := make(map[string][]*UserOAuthProvider)
		for i := range nodes {
			fk := nodes[i].UserID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.User = n
			}
		}
	}

	return nodes, nil
}

func (uopq *UserOAuthProviderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uopq.querySpec()
	_spec.Node.Columns = uopq.fields
	if len(uopq.fields) > 0 {
		_spec.Unique = uopq.unique != nil && *uopq.unique
	}
	return sqlgraph.CountNodes(ctx, uopq.driver, _spec)
}

func (uopq *UserOAuthProviderQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := uopq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (uopq *UserOAuthProviderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   useroauthprovider.Table,
			Columns: useroauthprovider.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: useroauthprovider.FieldID,
			},
		},
		From:   uopq.sql,
		Unique: true,
	}
	if unique := uopq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := uopq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useroauthprovider.FieldID)
		for i := range fields {
			if fields[i] != useroauthprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uopq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uopq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uopq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uopq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uopq *UserOAuthProviderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uopq.driver.Dialect())
	t1 := builder.Table(useroauthprovider.Table)
	columns := uopq.fields
	if len(columns) == 0 {
		columns = useroauthprovider.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uopq.sql != nil {
		selector = uopq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uopq.unique != nil && *uopq.unique {
		selector.Distinct()
	}
	for _, p := range uopq.predicates {
		p(selector)
	}
	for _, p := range uopq.order {
		p(selector)
	}
	if offset := uopq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uopq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserOAuthProviderGroupBy is the group-by builder for UserOAuthProvider entities.
type UserOAuthProviderGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uopgb *UserOAuthProviderGroupBy) Aggregate(fns ...AggregateFunc) *UserOAuthProviderGroupBy {
	uopgb.fns = append(uopgb.fns, fns...)
	return uopgb
}

// Scan applies the group-by query and scans the result into the given value.
func (uopgb *UserOAuthProviderGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := uopgb.path(ctx)
	if err != nil {
		return err
	}
	uopgb.sql = query
	return uopgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uopgb *UserOAuthProviderGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := uopgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (uopgb *UserOAuthProviderGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(uopgb.fields) > 1 {
		return nil, errors.New("ent: UserOAuthProviderGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := uopgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uopgb *UserOAuthProviderGroupBy) StringsX(ctx context.Context) []string {
	v, err := uopgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uopgb *UserOAuthProviderGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uopgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useroauthprovider.Label}
	default:
		err = fmt.Errorf("ent: UserOAuthProviderGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uopgb *UserOAuthProviderGroupBy) StringX(ctx context.Context) string {
	v, err := uopgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (uopgb *UserOAuthProviderGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(uopgb.fields) > 1 {
		return nil, errors.New("ent: UserOAuthProviderGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := uopgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uopgb *UserOAuthProviderGroupBy) IntsX(ctx context.Context) []int {
	v, err := uopgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uopgb *UserOAuthProviderGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uopgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useroauthprovider.Label}
	default:
		err = fmt.Errorf("ent: UserOAuthProviderGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uopgb *UserOAuthProviderGroupBy) IntX(ctx context.Context) int {
	v, err := uopgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (uopgb *UserOAuthProviderGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(uopgb.fields) > 1 {
		return nil, errors.New("ent: UserOAuthProviderGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := uopgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uopgb *UserOAuthProviderGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := uopgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uopgb *UserOAuthProviderGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uopgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useroauthprovider.Label}
	default:
		err = fmt.Errorf("ent: UserOAuthProviderGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uopgb *UserOAuthProviderGroupBy) Float64X(ctx context.Context) float64 {
	v, err := uopgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (uopgb *UserOAuthProviderGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(uopgb.fields) > 1 {
		return nil, errors.New("ent: UserOAuthProviderGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := uopgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uopgb *UserOAuthProviderGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := uopgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uopgb *UserOAuthProviderGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uopgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useroauthprovider.Label}
	default:
		err = fmt.Errorf("ent: UserOAuthProviderGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uopgb *UserOAuthProviderGroupBy) BoolX(ctx context.Context) bool {
	v, err := uopgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uopgb *UserOAuthProviderGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range uopgb.fields {
		if !useroauthprovider.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := uopgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uopgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (uopgb *UserOAuthProviderGroupBy) sqlQuery() *sql.Selector {
	selector := uopgb.sql.Select()
	aggregation := make([]string, 0, len(uopgb.fns))
	for _, fn := range uopgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(uopgb.fields)+len(uopgb.fns))
		for _, f := range uopgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(uopgb.fields...)...)
}

// UserOAuthProviderSelect is the builder for selecting fields of UserOAuthProvider entities.
type UserOAuthProviderSelect struct {
	*UserOAuthProviderQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (uops *UserOAuthProviderSelect) Scan(ctx context.Context, v interface{}) error {
	if err := uops.prepareQuery(ctx); err != nil {
		return err
	}
	uops.sql = uops.UserOAuthProviderQuery.sqlQuery(ctx)
	return uops.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uops *UserOAuthProviderSelect) ScanX(ctx context.Context, v interface{}) {
	if err := uops.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (uops *UserOAuthProviderSelect) Strings(ctx context.Context) ([]string, error) {
	if len(uops.fields) > 1 {
		return nil, errors.New("ent: UserOAuthProviderSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := uops.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uops *UserOAuthProviderSelect) StringsX(ctx context.Context) []string {
	v, err := uops.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (uops *UserOAuthProviderSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uops.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useroauthprovider.Label}
	default:
		err = fmt.Errorf("ent: UserOAuthProviderSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uops *UserOAuthProviderSelect) StringX(ctx context.Context) string {
	v, err := uops.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (uops *UserOAuthProviderSelect) Ints(ctx context.Context) ([]int, error) {
	if len(uops.fields) > 1 {
		return nil, errors.New("ent: UserOAuthProviderSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := uops.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uops *UserOAuthProviderSelect) IntsX(ctx context.Context) []int {
	v, err := uops.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (uops *UserOAuthProviderSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uops.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useroauthprovider.Label}
	default:
		err = fmt.Errorf("ent: UserOAuthProviderSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uops *UserOAuthProviderSelect) IntX(ctx context.Context) int {
	v, err := uops.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (uops *UserOAuthProviderSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(uops.fields) > 1 {
		return nil, errors.New("ent: UserOAuthProviderSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := uops.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uops *UserOAuthProviderSelect) Float64sX(ctx context.Context) []float64 {
	v, err := uops.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (uops *UserOAuthProviderSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uops.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useroauthprovider.Label}
	default:
		err = fmt.Errorf("ent: UserOAuthProviderSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uops *UserOAuthProviderSelect) Float64X(ctx context.Context) float64 {
	v, err := uops.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (uops *UserOAuthProviderSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(uops.fields) > 1 {
		return nil, errors.New("ent: UserOAuthProviderSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := uops.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uops *UserOAuthProviderSelect) BoolsX(ctx context.Context) []bool {
	v, err := uops.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (uops *UserOAuthProviderSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uops.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useroauthprovider.Label}
	default:
		err = fmt.Errorf("ent: UserOAuthProviderSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uops *UserOAuthProviderSelect) BoolX(ctx context.Context) bool {
	v, err := uops.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uops *UserOAuthProviderSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := uops.sql.Query()
	if err := uops.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
