// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sundaytycoon/buttons-api/ent/user"
	"github.com/sundaytycoon/buttons-api/ent/usermeta"
)

// UserMetaCreate is the builder for creating a UserMeta entity.
type UserMetaCreate struct {
	config
	mutation *UserMetaMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (umc *UserMetaCreate) SetUserID(s string) *UserMetaCreate {
	umc.mutation.SetUserID(s)
	return umc
}

// SetCreatedAt sets the "created_at" field.
func (umc *UserMetaCreate) SetCreatedAt(t time.Time) *UserMetaCreate {
	umc.mutation.SetCreatedAt(t)
	return umc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (umc *UserMetaCreate) SetNillableCreatedAt(t *time.Time) *UserMetaCreate {
	if t != nil {
		umc.SetCreatedAt(*t)
	}
	return umc
}

// SetCreatedBy sets the "created_by" field.
func (umc *UserMetaCreate) SetCreatedBy(s string) *UserMetaCreate {
	umc.mutation.SetCreatedBy(s)
	return umc
}

// SetUpdatedAt sets the "updated_at" field.
func (umc *UserMetaCreate) SetUpdatedAt(t time.Time) *UserMetaCreate {
	umc.mutation.SetUpdatedAt(t)
	return umc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (umc *UserMetaCreate) SetNillableUpdatedAt(t *time.Time) *UserMetaCreate {
	if t != nil {
		umc.SetUpdatedAt(*t)
	}
	return umc
}

// SetUpdatedBy sets the "updated_by" field.
func (umc *UserMetaCreate) SetUpdatedBy(s string) *UserMetaCreate {
	umc.mutation.SetUpdatedBy(s)
	return umc
}

// SetProfile sets the "profile" field.
func (umc *UserMetaCreate) SetProfile(s string) *UserMetaCreate {
	umc.mutation.SetProfile(s)
	return umc
}

// SetID sets the "id" field.
func (umc *UserMetaCreate) SetID(s string) *UserMetaCreate {
	umc.mutation.SetID(s)
	return umc
}

// SetUser sets the "user" edge to the User entity.
func (umc *UserMetaCreate) SetUser(u *User) *UserMetaCreate {
	return umc.SetUserID(u.ID)
}

// Mutation returns the UserMetaMutation object of the builder.
func (umc *UserMetaCreate) Mutation() *UserMetaMutation {
	return umc.mutation
}

// Save creates the UserMeta in the database.
func (umc *UserMetaCreate) Save(ctx context.Context) (*UserMeta, error) {
	var (
		err  error
		node *UserMeta
	)
	umc.defaults()
	if len(umc.hooks) == 0 {
		if err = umc.check(); err != nil {
			return nil, err
		}
		node, err = umc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserMetaMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = umc.check(); err != nil {
				return nil, err
			}
			umc.mutation = mutation
			if node, err = umc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(umc.hooks) - 1; i >= 0; i-- {
			if umc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = umc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, umc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (umc *UserMetaCreate) SaveX(ctx context.Context) *UserMeta {
	v, err := umc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (umc *UserMetaCreate) Exec(ctx context.Context) error {
	_, err := umc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (umc *UserMetaCreate) ExecX(ctx context.Context) {
	if err := umc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (umc *UserMetaCreate) defaults() {
	if _, ok := umc.mutation.CreatedAt(); !ok {
		v := usermeta.DefaultCreatedAt()
		umc.mutation.SetCreatedAt(v)
	}
	if _, ok := umc.mutation.UpdatedAt(); !ok {
		v := usermeta.DefaultUpdatedAt()
		umc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (umc *UserMetaCreate) check() error {
	if _, ok := umc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserMeta.user_id"`)}
	}
	if _, ok := umc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserMeta.created_at"`)}
	}
	if _, ok := umc.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "UserMeta.created_by"`)}
	}
	if _, ok := umc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserMeta.updated_at"`)}
	}
	if _, ok := umc.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "UserMeta.updated_by"`)}
	}
	if _, ok := umc.mutation.Profile(); !ok {
		return &ValidationError{Name: "profile", err: errors.New(`ent: missing required field "UserMeta.profile"`)}
	}
	if _, ok := umc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserMeta.user"`)}
	}
	return nil
}

func (umc *UserMetaCreate) sqlSave(ctx context.Context) (*UserMeta, error) {
	_node, _spec := umc.createSpec()
	if err := sqlgraph.CreateNode(ctx, umc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected UserMeta.ID type: %T", _spec.ID.Value)
		}
	}
	return _node, nil
}

func (umc *UserMetaCreate) createSpec() (*UserMeta, *sqlgraph.CreateSpec) {
	var (
		_node = &UserMeta{config: umc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: usermeta.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: usermeta.FieldID,
			},
		}
	)
	if id, ok := umc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := umc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: usermeta.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := umc.mutation.CreatedBy(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: usermeta.FieldCreatedBy,
		})
		_node.CreatedBy = value
	}
	if value, ok := umc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: usermeta.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := umc.mutation.UpdatedBy(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: usermeta.FieldUpdatedBy,
		})
		_node.UpdatedBy = value
	}
	if value, ok := umc.mutation.Profile(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: usermeta.FieldProfile,
		})
		_node.Profile = value
	}
	if nodes := umc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usermeta.UserTable,
			Columns: []string{usermeta.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserMetaCreateBulk is the builder for creating many UserMeta entities in bulk.
type UserMetaCreateBulk struct {
	config
	builders []*UserMetaCreate
}

// Save creates the UserMeta entities in the database.
func (umcb *UserMetaCreateBulk) Save(ctx context.Context) ([]*UserMeta, error) {
	specs := make([]*sqlgraph.CreateSpec, len(umcb.builders))
	nodes := make([]*UserMeta, len(umcb.builders))
	mutators := make([]Mutator, len(umcb.builders))
	for i := range umcb.builders {
		func(i int, root context.Context) {
			builder := umcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMetaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, umcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, umcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, umcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (umcb *UserMetaCreateBulk) SaveX(ctx context.Context) []*UserMeta {
	v, err := umcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (umcb *UserMetaCreateBulk) Exec(ctx context.Context) error {
	_, err := umcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (umcb *UserMetaCreateBulk) ExecX(ctx context.Context) {
	if err := umcb.Exec(ctx); err != nil {
		panic(err)
	}
}
